// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileType } from "./FileType";

export type FileInfo = { fileName: string | null, path: string, extension: string | null, fileType: FileType, size: bigint, lastModified: bigint | null, created: bigint | null, };
