// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QueryResultItem } from "./QueryResultItem";

export type QueryResult = { results: Array<QueryResultItem>, };