// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QueryResultType } from "./QueryResultType";
import type { ResultPreview } from "./ResultPreview";

export type QueryResultItem = { iconPath: string | null, heading: string, subheading: string, value: string, preview: ResultPreview | null, type: QueryResultType, };