// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QueryMode } from "./QueryMode";

export type Query = { search_string: string, mode: QueryMode, };