// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Query } from "./Query";
import type { WindowIdent } from "./WindowIdent";

export type ReceivedEvent = { "type": "Query", query: Query, } | { "type": "OpenWindow", window_ident: WindowIdent, } | { "type": "CloseWindow", window_ident: WindowIdent, } | { "type": "RunScript", script_name: string, };
