// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileType } from './FileType';

export type ResultPreview =
  | {
      type: 'File';
      path: string;
      filename: string | null;
      extension: string | null;
      fileType: FileType;
      size: string;
      lastModified: string | null;
      content: string;
      parsedContent: string | null;
    }
  | {
      type: 'BrowserHistory';
      url: string;
      imageUrl: string;
      heading: string;
      subheading: string;
    }
  | {
      type: 'Script';
      path: string;
      lastModified: string;
      language: string;
      content: string;
      parsedContent: string | null;
    }
  | { type: 'Calculator'; parsedContent: string };
