// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ResultDetails } from "./ResultDetails";
import type { ResultType } from "./ResultType";

export type ResultItem = { heading: string, subheading: string, value: string, iconPath: string | null, type: ResultType, details: ResultDetails | null, };
